### PR TITLE
Thickness null checks

### PR DESCRIPTION
**Pull request by dp901**

### CODE REVIEW

**Comment by BSick7** [comment]
I know it seems weird, but the null checks were left off intentionally.
Since `copyTo` is used during the pipeline execution, I aggressively pruned checks that were could incur penalties.

**Comment by BSick7** [comment]
Thanks for the PR though.
Is this causing issues for you?

**Comment by dp901** [comment]
Thanks for the reply Brad. Yes, this is causing issues. Rendering stops completely. Is it possible to somehow handle the exception? Adding the check allows the app to render normally.

**Comment by BSick7** [comment]
Can you send a stack trace of where this is originating?

**Comment by dp901** [comment]
TypeError: Cannot read property 'left' of undefined
    at Thickness.copyTo (Thickness.ts:23)
    at DependencyProperty.ChangedCallback (UIReaction.ts:42)
    at PropertyStore.OnPropertyChanged (PropertyStore.ts:167)
    at PropertyStore.ClearValue (PropertyStore.ts:136)
    at Border.DependencyObject.ClearValue (DependencyObject.ts:143)

The error is caused when our code calls ClearValue on BorderThickness, Margin or CornerRadius.

**Comment by BSick7** [comment]
Sorry for that issue.
It would be much more appropriate to adjust in `Fayde`.

**Comment by BSick7** [comment]
Closing in favor of https://github.com/wsick/Fayde/pull/271
Thanks again @dp901!

**Comment by BSick7** [comment]
See https://github.com/wsick/Fayde/blob/0.19.19/CHANGELOG.md#01919-mar-15-2017

**Comment by dp901** [comment]
Thanks Brad. Does the same fix apply to FrameworkElement MarginProperty?
Same error.

**Comment by BSick7** [comment]
It is not included.  Can you open an issue regarding this in Fayde please?

**Pull request closed without merging**
